ssiblog/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.index, name="index"),
    path("Login/", views.Login, name="Login"),
    path("Logout/", views.Logout, name="Logout"),
    path("authorize/", views.authorize, name="authorize"),
    path("seeContact/", views.seeContactForms, name="seeContact"),
    path("register/", views.Register, name="register"),
    path("approve/<id>/", views.approve, name="approve"),
    path("addPost/", views.addPost, name="addPost"),
    path('ContactForm/', views.ContactForm, name="ContactForm"),
    path('<slug:id>/', views.showSinglePost, name="singlePost"),
    path('edit/<int:pk>/', views.updatePost.as_view(), name="updatePost"),
    path('delete/<int:pk>/', views.deletePost.as_view(), name="deletePost"),
    path('deleteUser/<int:pk>/', views.deleteUser.as_view(), name="deleteUser"),
    path('tag/<slug:tag_slug>/', views.index, name="post_tag"),


]

ssiblog/ssiblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ssiblog/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from tinymce import models as tm_models
from taggit.managers import TaggableManager


class contactForm(models.Model):
    formEmail = models.EmailField()
    formMessage = models.TextField()

    def __str__(self):
        return self.formEmail + ' ' + self.formMessage


class beforeUser(models.Model):
    userName = models.TextField(unique=True)
    userPassword = models.TextField()
    userEmail = models.EmailField(unique=True)
    userActive = models.IntegerField(default=0)


    def __str__(self):
        return self.userName + ' ' + self.userEmail + ' ' + str(self.userActive)


class Post(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150, blank=True, unique_for_date='dateOfPublish')
    body = tm_models.HTMLField()
    image = models.ImageField(upload_to='images/', null=False,blank=False)
    dateOfPublish = models.DateTimeField(default=timezone.now)
    tags = TaggableManager()

    class Meta:
        ordering = ['-dateOfPublish']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:singlePost', args=[self.slug])


class Comments(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.CharField(max_length=50, default='Anonymous')
    body = models.TextField()

    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return self.body

# Create your models here.

ssiblog/blog/forms.py
from django import forms
from django.forms import TextInput
from .models import Comments, Post, contactForm
from captcha.fields import CaptchaField
from ckeditor.widgets import CKEditorWidget


class CForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = contactForm
        fields = [
            'formEmail',
            'formMessage']


class CommentForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Comments
        fields = ('body',)
        widgets = {
            'body': TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Skomentuj tutaj'
            })}


class addPostForm(forms.ModelForm):
    body = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Post
        fields = ['title', 'slug', 'body', 'image', 'tags', ]

ssiblog/blog/views.py
import json
from django.shortcuts import redirect, render, HttpResponse, get_object_or_404
from .models import *
from django.shortcuts import get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CForm, addPostForm, CommentForm
from django.views.generic import UpdateView, DeleteView
from taggit.models import Tag
from ckeditor.widgets import CKEditorWidget
from django import forms


class deleteUser(DeleteView):
    model = beforeUser
    template_name = 'deleteUser.html'
    success_url = "/authorize/"


def seeContactForms(request):
    see = contactForm.objects.all()
    return render(request, "seeContact.html", {'see':see})


def ContactForm(request):
    form = CForm()
    if request.method == "POST":
        form = CForm(data=request.POST)
        print("jej")
        if form.is_valid():
            form.save()
            return redirect("/")
    return render(request, "contact.html", {'form': form})


def approve(request, id):
    id = beforeUser.objects.get(id=id)
    username = id.userName
    print(username)
    emaiL = id.userEmail
    password = id.userPassword
    user = User.objects.create_user(username=username, email=emaiL, password=password)
    user.save()
    id.userActive = 1
    id.save()
    return redirect("/authorize/")


def Register(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password != confirm_password:
            messages.error(request, 'Hasła się nie są identyczne')
            return render(request, "register.html")
        try:
            new_user = beforeUser.objects.create(userName=username, userPassword=password, userEmail=email)
            new_user.save()
            return redirect("/")
        except:
            pass

    return render(request, "register.html")


def authorize(request):
    users = beforeUser.objects.filter(userActive=0)
    return render(request, 'authorize.html', {'users': users})


def Logout(request):
    logout(request)
    return redirect("/")


def Login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("/")

    return render(request, "login.html")


class deletePost(DeleteView):
    model = Post
    template_name = 'deletePost.html'
    success_url = "/"


class updatePost(UpdateView):
    body = forms.CharField(widget=CKEditorWidget())
    model = Post
    template_name = 'updatePost.html'
    fields = ['title', 'body', 'image', 'tags']


def addPost(request):
    add_Post = addPostForm()

    if request.method == 'POST' and request.FILES:
        upload = request.FILES
        add_Post = addPostForm(request.POST, upload)
        print(add_Post)
        if add_Post.is_valid():
            add_Post.save()
            return redirect("/")

    return render(request, "addPost.html", {'add_Post': add_Post})


def showSinglePost(request, id):
    post = get_object_or_404(Post, slug=id, )
    posts = Post.objects.filter(slug=id)
    comments = Comments.objects.filter(post=posts[0])
    new_comment = None
    print(posts)
    comment_form = CommentForm()
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            if request.user.is_authenticated:
                new_comment.author = request.user.username
            new_comment.post = get_object_or_404(Post, slug=id, )
            new_comment.save()
            return redirect(post.get_absolute_url())
        else:
            comment_form = CommentForm()
    return render(request, 'singlePost.html', {'posts': posts, 'comments': comments, 'comment_form': comment_form})


def index(request, tag_slug=None):
    posts = Post.objects.all()
    page = request.GET.get('page', 1)
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])

    paginator = Paginator(posts, 3)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, "index.html", {'posts': posts, 'tag': tag, 'page': page})

# Create your views here.

ssiblog/blog/templates/addPost.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Mechanical Keyboard Blog {% endblock %}
{% block body %}

<h3>Dodaj Post</h3>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ add_Post.as_p}}<br>
    {{ add_Post.media}}<br>
    <button type="submit" class="btn btn-primary">Dodaj</button>
</form>

{% endblock %}

ssiblog/blog/templates/authorize.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Mechanical Keyboard Blog {% endblock %}
{% block body %}
<div class="container mt-4">
    <h1 class="text-center"><u>Lista użytkowników do akceptacji</u></h1>
    <table class="table table-hover" id="example">
        <thead>
            <tr>
                <th>Numer.Index</th>
                <th>Użytkownik</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            {% for u in users %}
            <tr>
                <td>{{forloop.counter}}.</td>
                <td>{{u.userName}}</td>
                <td>{{u.userEmail}}</td>
                <td><a href="/approve/{{u.id}}/" class="btn btn-primary" onclick="return confirm('Czy na pewno dodać użytkownika')">Dodaj</a>&nbsp;
                <a href="/deleteUser/{{u.pk}}/" class="btn btn-danger">Usuń</a></td>
            {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

ssiblog/blog/templates/base.html
<!doctype html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>{% block title %} {% endblock %}</title>
    {% block css %}
    {% endblock %}
    {% load static %}
  </head>
  <body>
      <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

      <!-- Container wrapper -->
      <div class="container-fluid">
          <a class="navbar-brand" href="/">
           <img src="{% static 'images/mk.png' %}" width="30" height="30" alt="">
          </a>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="/ContactForm/">Formularz kontakowy</a>
            </li>
          </ul>
            {% if user.is_authenticated %}
                <button class="btn btn-outline-info my-2 my-sm-0" onclick="document.location='/Logout/'">Zalogowany {{user}}</button>&nbsp;
              {% else %}
                <button class="btn btn-outline-info my-2 my-sm-0" onclick="document.location='/Login/'">Zaloguj</button>&nbsp;
              {% endif %}
              {% if user.is_superuser %}
              <button class="btn btn-outline-dark my-2 my-sm-0" onclick="document.location='/seeContact/'">Wiadomości</button>&nbsp;
              <button class="btn btn-outline-dark my-2 my-sm-0" onclick="document.location='/authorize/'">Autoryzuj Użytkowników</button>&nbsp;
              <button class="btn btn-outline-success my-2 my-sm-0" onclick="document.location='/addPost/'">Dodaj post</button>
              {% endif %}
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
    <main class="container my-3">
      {% block body %}
      {% endblock %}
    </main>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    {% block js %}
    {% endblock %}
  </body>
</html>

ssiblog/blog/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Mechanical Keyboard Blog {% endblock %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    <div class="container"> <div class=" text-center mt-5 ">
            <h1>Formularz Kontaktowy</h1>
        {% csrf_token %}
        </div>
        <div class="row ">
            <div class="col-lg-7 mx-auto">
                <div class="card mt-2 mx-auto p-4 bg-light">
                    <div class="card-body bg-light">
                        <div class="container">
                            <form id="contact-form" role="form">
                                <div class="controls">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Podaj adres Email</label>
                                            <div class="form-group"> {{ form.formEmail }} </div>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <label>Wpisz wiadomość </label>
                                            <div class="form-group"> {{ form.formMessage }} </div>
                                            <br>
                                        </div>
                                        <div class="col-md-12"> <button type="submit" class="btn btn-success btn-send pt-2 btn-block ">Wyślij wiadomość</button> {{ form.captcha }} </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div> <!-- /.8 -->
            </div> <!-- /.row-->
        </div>
    </div>
</form>
{% endblock %}

ssiblog/blog/templates/deletePost.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Mechanical Keyboard Blog {% endblock %}
{% block body %}


<h3>Usuń Post {{post.title}}</h3>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-warning">Usuń</button>
</form>

{% endblock %}

ssiblog/blog/templates/deleteUser.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Mechanical Keyboard Blog {% endblock %}
{% block body %}


<h3>Usuń Użytkownika {{u.userName}}</h3>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-warning">Usuń</button>
</form>

{% endblock %}

ssiblog/blog/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Mechanical Keyboard Blog {% endblock %}
{% block body %}
{% if tag %}
<h2 class="mb-3">Posts tagged with "{{ tag.name }}"</h2>
{% endif %}
{% for post in posts %}
<div class="card mb-3">
    <div class="card-body container">
        <div class="row">
            <div class="col-md-3">
                {% if post.image.url %}
                 <img src="{{post.image.url}}" class="img-thumbnail " alt="{{post.title}}">
                {% endif %}
            </div>
            <div class="col-md-6">
                <h2 class="card-title h5">
                    <a href="{{post.get_absolute_url}}">
                        {{post.title}}
                    </a>
                </h2>
                <div class="text_muted">
                    <small>
                        Opublikowano: {{post.dateOfPublish.date}}
                    </small>
                </div>
                <p class="card-text mb-auto py-2">{{post.body|safe|striptags|truncatechars:100}}</p>
                <div>
                    <a href="{{post.get_absolute_url}}" class="btn btn-primary btn-sm">Więcej</a>
                    {% if user.is_superuser %}
                    <a href="edit/{{post.pk}}/" class="btn btn-warning btn-sm">Edytuj</a>
                    <a href="delete/{{post.pk}}/" class="btn btn-danger btn-sm">Usuń</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endfor %}

{% if posts.has_other_pages %}
  <ul class="pagination">
    {% if posts.has_previous %}
      <li><a href="?page={{ posts.previous_page_number }}" class="btn btn-dark">&laquo;</a></li>
    {% else %}
      <li class="disabled btn btn-dark"><span>&laquo;</span></li>
    {% endif %}
    {% for i in books.paginator.page_range %}
      {% if posts.number == i %}
        <li class="active btn btn-dark"><span>{{ i }} <span class="sr-only"></span></span></li>
      {% else %}
        <li><a href="?page={{ i }}" class="btn btn-dark">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if posts.has_next %}
      <li><a href="?page={{ posts.next_page_number }}" class="btn btn-dark">&raquo;</a></li>
    {% else %}
      <li class="disabled btn btn-dark"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{% endblock %}

ssiblog/blog/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Mechanical Keyboard Blog {% endblock %}
{% block body %}
<div class="container">
<br>
<h1 class="text-center"><u>Login</u></h1><br>
    <form method="POST"> {% csrf_token %}

    <div class="row mt-4">
        <div class="form-group col-md-12">
            <label><i style="font-weight: bold;">Login</i></label>
            <input type="text" class="form-control mt-2" name="username" placeholder="Wprowadź Nazwę Użytkownika" required>
        </div>
    </div>

    <div class="row mt-4">
        <div class="form-group col-md-12">
            <label><i style="font-weight: bold;">Hasło</i></label>
            <input type="password" class="form-control mt-2" name="password" placeholder="Wprowadź Hasło" required>
        </div>
    </div>
    <button type="submit" class="btn btn-outline-primary mt-4">Login</button>
</div>
<br>
<br>
<div class="text-center">
    <p>Nie masz jeszcze konta ?</p>
    <form>
        <button  onclick="document.location='/register/'" class="btn btn-outline-success mt-4">Zarejestruj się</button>
    </form>
</div>
{% endblock %}

ssiblog/blog/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Mechanical Keyboard Blog {% endblock %}
{% block body %}
<div class="container">
    <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
        <br>
        <h1 class="text-center"><u>Rejestracja Użytkownika</u></h1>
    <div class="row mt-4">
        <div class="form-group col-md-12">
            <label><i style="font-weight: bold;">Nazwa Użytkownika</i></label>
            <input type="text" class="form-control mt-2" name="username" placeholder="Wprowadź Nazwę Użytkownika" required>
        </div>
    </div>
    <div class="row mt-4">
        <div class="form-group col-md-6">
            <label><i style="font-weight: bold;">Email</i></label>
            <input type="email" class="form-control mt-2" name="email" placeholder="Podaj Email" required>
        </div>
    </div>
    <div class="row mt-4">
        <div class="form-group col-md-6">
            <label><i style="font-weight: bold;">Hasło</i></label>
            <input type="password" class="form-control mt-2" name="password" placeholder="Wprowadź Hasło" required>
        </div>
        <div class="form-group col-md-6">
            <label><i style="font-weight: bold;"Potwierdź Hasło</i></label>
            <input type="password" class="form-control mt-2" name="confirm_password" placeholder="Potwierdź Hasło" required>
        </div>
    </div>
    <button type="submit" class="btn btn-outline-primary mt-4">Zarejestruj się</button>
</div>
</form>
<div class="text-center">
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}
</div>
{% endblock %}

ssiblog/blog/templates/seeContact.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Mechanical Keyboard Blog {% endblock %}
{% block body %}
<div class="container mt-4">
    <h1 class="text-center"><u>Lista Wiadomości</u></h1>
    <table class="table table-hover" id="example">
        <thead>
            <tr>
                <th>Numer.Index</th>
                <th>Email</th>
                <th>Wiadomość</th>
            </tr>
        </thead>
        <tbody>
            {% for s in see %}
            <tr>
                <td>{{forloop.counter}}.</td>
                <td>{{s.formEmail}}</td>
                <td>{{s.formMessage}}</td>
            {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

ssiblog/blog/templates/singlePost.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{post.title}} {% endblock %}
{% block body %}
{% for post in posts %}
    <article>
        <figure>
         <img src="{{post.image.url}}" class="rounded img-fluid" alt="{{post.title}}">
        </figure>
        <div class="mt-3">
            <h1>{{post.title}}</h1>
            <p class="text-muted">
                Opublikowano {{ post.dateOfPublish.date }}
            </p>
        </div>
        <div class="article-body">
                {{post.body|safe|linebreaks}}
        </div>
    <p>
        <strong>Tags:</strong>
        {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_tag' tag.slug %}" class="link-light text-decoration-none badge bg-secondary">
                {{tag.name}}
            </a>
        {% endfor %}
    </p>

    </article>
{% endfor %}
<hr/>
        <h3>Dodaj Komentarz</h3>
        <form method="post" action="">
            {% csrf_token %}
            {{ comment_form.body }}<br>
            <button type="submit" class="btn btn-primary">Dodaj</button> {{ comment_form.captcha }}<br>
        </form>

        {% with comments.count as total_comments %}
            <h3 class="mt-5">
                {{ total_comments }} komentarze
            </h3>
        {% endwith %}
        {% for comment in comments %}
        <div class="border-0 border-start border-2 ps-2" id="{{comment.id}}">
        <div class="mt-3">
            <strong>{{comment.author}}</strong>
            <small class="text-muted">On {{ comment.created.date }}</small>
        </div>
        <div class="border p-2 rounded">
            <p>{{comment.body}}</p>
                    </div>
                </form>
            </div>
        </div>
        {% endfor %}


{% endblock %}

ssiblog/blog/templates/updatePost.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Mechanical Keyboard Blog {% endblock %}
{% block body %}
<h3>Edytuj Post</h3>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p}}<br>
    {{ form.media}}<br>
    <button type="submit" class="btn btn-primary">Edytuj</button>
</form>

{% endblock %}